name: pull_request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: kikobeats/docker-vips:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Pretest
        run: |
          vips -v
          convert --version
          convert -list format
          convert -list configure
      - name: Test
        run: pnpm test
      - name: Report
        run: npx c8 report --reporter=text-lcov > coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
